//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPm.FolderClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookOrder
    {
        public Nullable<int> IdBook { get; set; }
        public Nullable<int> IdOrder { get; set; }
        public int ID { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Order Order { get; set; }
    }
}
