//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPm.FolderClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.BookOrder = new HashSet<BookOrder>();
        }
    
        public int IdOrder { get; set; }
        public Nullable<System.DateTime> DateMarket { get; set; }
        public Nullable<System.DateTime> DateStock { get; set; }
        public Nullable<System.DateTime> DateReservation { get; set; }
        public Nullable<int> CountBook { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookOrder> BookOrder { get; set; }
    }
}
